### ISSUE TITLE
level2 페어 코드리뷰 - 강경원

### ISSUE THREAD

**Issue by Rose-Rosie-Rose** [gunhoray/MYTODOLIST-LV2#4]
정말 깔끔한 코드를 볼 수 있어서 너무 감사합니다!!!그리고 덤으로 너무 이쁜 todo 페이지를 볼 수 있게 되어서 넘 영광입니다!!

- inputbox.jsx에서 사용하는 useState의 내용을 하나의 객체로 받아와서 관리하는건 어떤가 생각이 들었습니다.
그 부분에서 하나의 useState로 관리를 하게 된다면 input의 onchange 이벤트에서 하나의 함수만 생성하여 그 함수를 재사용할 수 있지 않을까 생각이 들었습니다
- todo input 데이터를 props로 받아와서 한 번에 redux에서 관리하는 방법을 새롭게 알게 될 수 있어서 감사합니다
이 방법을 통해서 초기 상태 값을 하나로 관리할 수 있다는 걸 알 수 있어서 너무 좋았습니다.
- id를 부여하는 방법에서 uuid라는 패키지를 사용하신 걸 보고 id를 부여할 수 있는 새로운 방법을 배울 수 있었습니다.
- style을 한 파일에 작성하셨는데 지금 사용하는 방법도 너무 좋지만 재사용을 해야 되는 컴포넌트들만 따로 분리해서 사용하는건 어떤가 생각이 들었습니다.
그렇게 분리해서 사용하면 지금은 몇 개 안되는 sytle이여서 괜찮을 거 같은데 만들어야 되는 양이 커지게 된다면 나중에 재사용을 해야 되는 컴포넌트들의 수정이 조금 더 용이하지 않을까라는 생각이 들었습니다.

너무나도 코드가 깔끔하고 누구나 쉽게 보자마자 이해할 수 있는 코드를 작성해 주셔서 읽는데도 너무 편하고 좋았습니다!!
이렇게도 폴더 구조와 컴포넌트 단위를 나눌 수도 있다는걸 알게 되어서 너무 좋았습니다.
또 정말 css를 어떻게 사용하는지 정말 하나하나 뜯어보고 너무 많은 것을 배울 수 있게 해주셔서 너무 감사합니다!!!

**Comment by gunhoray** [comment]
GOLD 같은 리뷰 정말 감사합니다~!!
역시 서로 다른 시각은 다양한 로직을 만들어 내는 것 같습니다. 
refactoring을 하며 꼭 반영해 보겠습니다!! 
감사합니다!
