### ISSUE TITLE
LV2 페어 코드리뷰 육정백

### ISSUE THREAD

**Issue by SAHA-YJB** [gunhoray/MYTODOLIST-LV2#5]
저희 페어와는 다른 코드를 볼 수 있는 기회에 감사드리고 많은 것을 배웠던 것 같습니다. 감사합니다.!

폴더구조
구조를 깔끔하게 잘 나누어 놓았다고 생각했고, 
저희 페어는 폴더이름으로 관리했다면 건호 승현님은
컴포넌트 파일명으로 나누어 놓으셔서 직관적인 방법이었다고 생각합니다!!

리덕스
전체적으로 깔끔하고 알아보기 용이했고,
간단한 주석으로 인해 무엇을 받아오는지,
간략하게 설명해주시는 것도 좋았습니다!!

라우터
기본 적용 방식과 동적라우팅을 활용해 id값을 보여주는
방식은 추후 페이지 추가를 할 때 원활하게 진행을 이어나갈 수 있을 것 같다고 생각했습니다!!

상세페이지
find메서드를 활용하여 작성하신 것은 몰랐던 방식이라,
filter말고도 다양한 방식이 있구나 하며 많이 배웠습니다!!

메인페이지
uuid라이브러리를 사용하여 고유값을 부여하는 방식은 저희 페어와 차이가 있어
라이브러리 활용을 적극 고려해야겠다고 생각했습니다!!
또한 삭제 시 confirm을 사용해 다시 한번 확인하는 것은 ux에 많이 적합하다고 생각했습니다.

스타일
너무 멋진 스타일.....!!!!
한가지 궁금한점은 한 파일 안에서 관리하셨는데 혹시나,
페이지가 늘어나 사용해야할 스타일이 늘어난다면 보기 조금 어려울 수 있지않을까?
하는 생각이 들었습니다!!
(그렇지만 스타일 너무 멋쪄여!!)

**Comment by gunhoray** [comment]
좋은 리뷰 너무 감사합니다~!
스타일이 마음에 드셨다니 저도 기분이 좋습니다. ^^
refactoring을 진행할 때, 혹은 다음 프로젝트 때, 꼭 반영하겠습니다.
감사합니다~!
